(define (problem aoc16) (:domain aoc16_domain)
(:objects AA BB CC DD EE FF GG HH II JJ - field
          human - player
)

(:init
    (neighbor AA DD)
    (neighbor AA II)
    (neighbor AA BB)
    (neighbor BB CC)
    (neighbor BB AA)
    (neighbor CC DD)
    (neighbor CC BB)
    (neighbor DD CC)
    (neighbor DD AA)
    (neighbor DD EE)
    (neighbor EE FF)
    (neighbor EE DD)
    (neighbor FF EE)
    (neighbor FF GG)
    (neighbor GG FF)
    (neighbor GG HH)
    (neighbor HH GG)
    (neighbor II AA)
    (neighbor II JJ)
    (neighbor JJ II)
    (on human AA)
    (= (flow-total) 0)
    (= (time) 30)
    (= (flow-value AA) 0)
    (= (flow-value BB) 13)
    (= (flow-value CC) 2)
    (= (flow-value DD) 20)
    (= (flow-value EE) 3)
    (= (flow-value FF) 0)
    (= (flow-value GG) 0)
    (= (flow-value HH) 22)
    (= (flow-value II) 0)
    (= (flow-value JJ) 21)
    (closed AA)
    (closed BB)
    (closed CC)
    (closed DD)
    (closed EE)
    (closed FF)
    (closed GG)
    (closed HH)
    (closed II)
    (closed JJ)
)

(:goal (and
    (= (time) 0)
    ; (closed JJ)
))

(:metric maximize (flow-total))
)
